service:
  name: basic-serverless

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: src/functions/handler.hello
    events:
      - http:
         method: get
         path: hello