service:
  name: basic-serverless

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  GetGroups:
   handler: src/lambda/http/getGroups.handler
   events:
    - http:
       method: get
       path: groups
       cors: true